name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Copy files via SCP
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "."
      #     target: "/opt/docker/Noblestride/backend/noble_backend"

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 30m
          script: |
            echo 'Connecting to server...'
            cd ../opt/docker/Noblestride/backend/noble_backend
            echo 'Pulling latest changes...'
            git pull origin main
            echo 'Building and starting containers...'
            docker-compose build app
            docker-compose run --rm app npx sequelize-cli db:migrate
            docker-compose run --rm app npx sequelize-cli db:seed:all
            docker-compose up -d app > /dev/null 2>&1 &

      - name: Health Check
        run: |
          echo "Waiting for services to start..."
          sleep 15
          echo "Performing health check on ${{ secrets.DEV_URL }}"
          curl -f ${{ secrets.DEV_URL }}
